enum RATING {
	TOTAL = 'TOTAL',
	SCREENPLAY = 'SCREENPLAY',
	ACTING = 'ACTING',
	SHOOTING = 'SHOOTING',
	DECORATION = 'DECORATION',
	SOUNDTRACK = 'SOUNDTRACK',
	SPECIAL_EFFECTS = 'SPECIAL_EFFECTS',
	ATMOSPHERE = 'ATMOSPHERE',
	// EMOTIONAL_EFFECT = 'EMOTIONAL_EFFECT',
}

export { RATING };
