export const ROUTE = {
	HOME: '/',
	ERROR: '*',
	ADMIN: 'admin-panel',
	GENRES: 'genres',
	MOVIES: 'movies',
	ROLES: 'roles',
	PERSONS: 'persons',
	COLLECTION: 'my-collection',
	CATEGORIES: 'my-collection/categories',
	PROFILE: 'profile/:id',
	MOVIE_PAGE: 'movies/:id',
	PERSON_PAGE: 'person/:id',
	LOGIN: 'login',
	REGISTRATION: 'registration',
};
