export const ROUTE = {
	HOME: '/',
	ERROR: '*',
	ADMIN: 'admin-panel',
	GENRES: 'genres',
	MOVIES: 'movies',
	ROLES: 'roles',
	PERSONS: 'persons',
	COLLECTION: 'my-collection',
	CATEGORIES: 'my-collection/categories',
	GRADE_HISTORY: '/my-collection/grade-histroy',
	PROFILE_COLLECTION: 'profile/collection/:id',
	PROFILE_GRADE_HISTORY: '/profile/grade-histroy/:id',
	MOVIE_PAGE: 'movies/:id',
	PERSON_PAGE: 'person/:id',
	LOGIN: 'login',
	REGISTRATION: 'registration',
};
