const MAIN_CREATORS = {
	GENRE: 'genre/',
	AUTH: 'auth/',
	MOVIE: 'movie/',
};

const GENRE_CREATOR = {
	GET_ALL: `${MAIN_CREATORS.GENRE}getAll`,
	ADD: `${MAIN_CREATORS.GENRE}addGenre`,
	EDIT: `${MAIN_CREATORS.GENRE}editGenre`,
	DELETE: `${MAIN_CREATORS.GENRE}deleteGenre`,
};

const AUTH_CREATOR = {
	LOGIN: `${MAIN_CREATORS.AUTH}login`,
	REGISTRATION: `${MAIN_CREATORS.AUTH}registration`,
};

const MOVIE_CREATOR = {
	GET_FORM_DATA: `${MAIN_CREATORS.MOVIE}getFormData`,
	ADD: `${MAIN_CREATORS.MOVIE}add`,
	GET_BY_ID: `${MAIN_CREATORS.MOVIE}getById`,
};

export { GENRE_CREATOR, AUTH_CREATOR, MOVIE_CREATOR };
