const MAIN_CREATORS = {
	GENRE: 'genre/',
	AUTH: 'auth/',
	FILM: 'movie/',
};

const GENRE_CREATOR = {
	GET_ALL: `${MAIN_CREATORS.GENRE}getAll`,
	ADD: `${MAIN_CREATORS.GENRE}addGenre`,
	EDIT: `${MAIN_CREATORS.GENRE}editGenre`,
	DELETE: `${MAIN_CREATORS.GENRE}deleteGenre`,
};

const AUTH_CREATOR = {
	LOGIN: `${MAIN_CREATORS.AUTH}login`,
	REGISTRATION: `${MAIN_CREATORS.AUTH}registration`,
};

const FILM_CREATOR = {
	GET_FORM_DATA: `${MAIN_CREATORS.FILM}getFormData`,
	ADD: `${MAIN_CREATORS.FILM}add`,
};

export { GENRE_CREATOR, AUTH_CREATOR, FILM_CREATOR };
