const MAIN_CREATORS = {
	GENRE: 'genre/',
	USER: 'user/',
	MOVIE: 'movie/',
	PERSON: 'person/',
	RATING: 'rating/',
	CATEGORY: 'category/',
	SEARCH: 'search/',
};

const GENRE_CREATOR = {
	GET_ALL: `${MAIN_CREATORS.GENRE}getAll`,
	ADD: `${MAIN_CREATORS.GENRE}add`,
	EDIT: `${MAIN_CREATORS.GENRE}edit`,
	DELETE: `${MAIN_CREATORS.GENRE}delete`,
};

const USER_CREATOR = {
	LOGIN: `${MAIN_CREATORS.USER}login`,
	REGISTRATION: `${MAIN_CREATORS.USER}registration`,
	SET_ROLE: `${MAIN_CREATORS.USER}setRole`,
	GET_DATA: `${MAIN_CREATORS.USER}getData`,
	UPDATE_ROLE: `${MAIN_CREATORS.USER}updateRole`,
	GRADE_HISTORY: `${MAIN_CREATORS.USER}gradeHistory`,
};

const MOVIE_CREATOR = {
	GET_FORM_DATA: `${MAIN_CREATORS.MOVIE}getFormData`,
	ADD: `${MAIN_CREATORS.MOVIE}add`,
	GET_BY_ID: `${MAIN_CREATORS.MOVIE}getById`,
	GET_CATEGORIES: `${MAIN_CREATORS.MOVIE}getCategories`,
	DELETE: `${MAIN_CREATORS.MOVIE}delete`,
	UPDATE: `${MAIN_CREATORS.MOVIE}update`,
	SET_IMAGES: `${MAIN_CREATORS.MOVIE}setImages`,
};

const PERSON_CREATOR = {
	ADD: `${MAIN_CREATORS.PERSON}add`,
	UPDATE: `${MAIN_CREATORS.PERSON}update`,
	GET: `${MAIN_CREATORS.PERSON}get`,
	DELETE: `${MAIN_CREATORS.PERSON}delete`,
	SET_IMAGES: `${MAIN_CREATORS.PERSON}setImages`,
};

const RATING_CREATOR = {
	SET: `${MAIN_CREATORS.RATING}set`,
	UPDATE: `${MAIN_CREATORS.RATING}update`,
	DELETE: `${MAIN_CREATORS.GENRE}delete`,
};

const CATEGORY_CREATOR = {
	GET_ALL: `${MAIN_CREATORS.CATEGORY}getAll`,
	ADD: `${MAIN_CREATORS.CATEGORY}add`,
	EDIT: `${MAIN_CREATORS.CATEGORY}edit`,
	DELETE: `${MAIN_CREATORS.CATEGORY}delete`,
	ADD_MOVIE: `${MAIN_CREATORS.CATEGORY}addMovie`,
	GET_MOVIES: `${MAIN_CREATORS.CATEGORY}getMovies`,
	DELETE_MOVIE: `${MAIN_CREATORS.CATEGORY}deleteMovie`,
};

const SEARCH_CREATOR = {
	SET_VALUE: `${MAIN_CREATORS.SEARCH}setValue`,
};

export {
	GENRE_CREATOR,
	USER_CREATOR,
	MOVIE_CREATOR,
	PERSON_CREATOR,
	RATING_CREATOR,
	SEARCH_CREATOR,
	CATEGORY_CREATOR,
};
