spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movie-aggregator}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      auto-commit: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: edu.sstu.platform.config.CustomPostgreSQL95Dialect
        search:
          backend:
            directory:
              root: ${user.dir}/BE/platform/lucene/indexes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    locale: ru

springdoc:
  api-docs:
    path: /api/docs

app:
  api:
    countries: https://namaztimes.kz/ru/api/country
    omdb: http://www.omdbapi.com?i=tt%s&apikey=${OMDB_API_KEY}
    kinopoisk: https://rating.kinopoisk.ru/%s.xml
  url-pattern:
    metacritic: https://www.metacritic.com/movie/%s/
  default-categories: ${DEFAULT_CATEGORIES:Буду смотреть, Любимое}

job:
  movie-external-info-refresh:
    cron: ${MOVIE_EXTERNAL_INFO_REFRESH_JOB_CRON:0 0 * * * *}
    enabled: ${MOVIE_EXTERNAL_INFO_REFRESH_JOB_ENABLED:true}
