spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movie-aggregator}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api/docs
